name: Build and Deploy to Minikube

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Java and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Web Application Archive (WAR)
      run: mvn -f pom.xml clean package

    - name: Point Docker to Minikube & Build Image
      shell: powershell
      run: |
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression
        docker build -t local/simple-servlet:latest .

    - name: Deploy to Minikube
      shell: powershell
      run: |
        kubectl apply -f k8s/servlet-deployment.yaml
        kubectl rollout restart deployment/servlet-deployment
