name: Compile and Deploy to Local Tomcat

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Build Web Application Archive (WAR)
      run: |
        cd simple-servlet
        mvn clean package

    - name: List target directory
      run: dir simple-servlet\target

    - name: Deploy to Local Tomcat Webapps
      run: |
        Copy-Item "simple-servlet\target\simple-servlet-0.1.war" -Destination "C:\Users\hp\Downloads\apache-tomcat-10.1.57\webapps" -Force
